

#if !defined(AFX_IUICLIENT_H__E1C796E6_2A3A_11D3_8F7E_00E09802EAB8__INCLUDED_)
#define AFX_IUICLIENT_H__E1C796E6_2A3A_11D3_8F7E_00E09802EAB8__INCLUDED_

//--------------
// IUIClient
//   Catches events generated by the CoffeeMaker UI.

namespace com_cmindustries_coffeeMakerFSM
{
    class IUIClient;
};

class com_cmindustries_coffeeMakerFSM::IUIClient  
{
public:
	virtual ~IUIClient();

    virtual void Start() = 0;
};

#endif // !defined(AFX_IUICLIENT_H__E1C796E6_2A3A_11D3_8F7E_00E09802EAB8__INCLUDED_)
